name: Backend - production

on: 
  push:
    branches: [ main ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create archive
        run: |
          mkdir output
          zip -r output/minha-ia-api.zip . > output.txt
          ls -lah output

      - name: Send To FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with: 
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./output/
          server-dir: /apiminhaiafit/

      - name: Connect to server via SSH
        uses: tiyee/action-ssh@v1.0.1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          port: ${{ secrets.PRO_SSH_PORT }}
          privateKey: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          command: |
            cd /home/u736474566/domains/sistemasgu.com/public_html/apiminhaiafit/
            unzip -o minha-ia-api.zip
            php composer.phar install
